### ISSUE TITLE
[Q&A] How to run, integrate to Android

### ISSUE THREAD

**Issue by truongnmt** [Warchant/iroha-pure-java#7]
On clone repo and import to Intellij IDEA, I don't know how to dev/test in integration. By the way, how can I integrate this into Android project. Since I can't make [iroha-android repo](https://github.com/hyperledger/iroha-android) works.

**Comment by Warchant** [comment]
Since Iroha is written in C++, the team has developed a C++ client library for it (shared_model). To save the time on client library development, they integrated automatic SWIG bindings generation for java, python and nodejs. 

I personally don't like JNI in java code, so I wrote this library.

I test the library in the following way:
1. create [`transaction1`](https://github.com/Warchant/iroha-pure-java/blob/master/src/integration/java/jp/co/soramitsu/withbindings/TransactionTest.java#L65-L86) with swig java bindings and [`transaction2`](https://github.com/Warchant/iroha-pure-java/blob/master/src/integration/java/jp/co/soramitsu/withbindings/TransactionTest.java#L47-L62) with `iroha-pure-java` lib
2. serialize them to protobuf
3. [if they are equal](https://github.com/Warchant/iroha-pure-java/blob/master/src/integration/java/jp/co/soramitsu/withbindings/TransactionTest.java#L98), integration test is passed.

You can find integration tests here https://github.com/Warchant/iroha-pure-java/tree/master/src/integration/java/jp/co/soramitsu/withbindings

and execute them with `gradle integration`. 

To successfully execute integration tests, you need to build [`libirohajava`](https://github.com/hyperledger/iroha/tree/master/example/java) and put it to according folder: 
```
https://github.com/Warchant/iroha-pure-java/tree/master/bindings/{platform}/{version}/
```
You can notice there are pre-built libraries. They **may** work for you, but it is not guaranteed.

To integrate your library you need to use jitpack: https://jitpack.io/#warchant/iroha-pure-java

**Comment by truongnmt** [comment]
Thanks for a detail answer 🙌
